services:
  bambu-timelapse-downloader:
    build: .
    container_name: bambu-timelapse-downloader
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - ./downloads:/downloads
